eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
spring:
   application:
      name: transactionhistoryservice
   data:
    mongodb:
      uri: mongodb+srv://admin:admin@spendanalyser.uvydn.mongodb.net/SPENDANALYSER?retryWrites=true&w=majority
server:
   port: 9002
  

